// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-DeLuVXukfOhjWvm0hAc5XjHhfJqmLsg',
    appId: '1:189160314701:web:7df2cb9300984f5942c904',
    messagingSenderId: '189160314701',
    projectId: 'medvault-application-e58be',
    authDomain: 'medvault-application-e58be.firebaseapp.com',
    storageBucket: 'medvault-application-e58be.firebasestorage.app',
    measurementId: 'G-FW95HB6YG8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzZlmFg9-QUYXKBKDCYUHPMWm_n-63Isw',
    appId: '1:189160314701:android:0efadbcfe503e85542c904',
    messagingSenderId: '189160314701',
    projectId: 'medvault-application-e58be',
    storageBucket: 'medvault-application-e58be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg5OoWTgVkaQgPrsY4hIy7EDZ0GLgeYwM',
    appId: '1:189160314701:ios:17d31b7d4c64c67742c904',
    messagingSenderId: '189160314701',
    projectId: 'medvault-application-e58be',
    storageBucket: 'medvault-application-e58be.firebasestorage.app',
    androidClientId: '189160314701-2dp95c8mpsoppl5tl8dhkc40diesb9je.apps.googleusercontent.com',
    iosClientId: '189160314701-2527h7v24iak5053s57bk2vl8v4to61s.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthvaults',
  );
}
